# Generated by Django 4.1.5 on 2023-01-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="shippingaddress", name="order",),
        migrations.RenameField(
            model_name="order", old_name="paymentMethod", new_name="address",
        ),
        migrations.RemoveField(model_name="order", name="deliveredAt",),
        migrations.RemoveField(model_name="order", name="isDelivered",),
        migrations.RemoveField(model_name="order", name="isPaid",),
        migrations.RemoveField(model_name="order", name="paidAt",),
        migrations.RemoveField(model_name="order", name="shippingPrice",),
        migrations.RemoveField(model_name="order", name="taxPrice",),
        migrations.RemoveField(model_name="order", name="totalPrice",),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="postalCode",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(name="OrderItem",),
        migrations.DeleteModel(name="ShippingAddress",),
    ]
