# Generated by Django 4.1.5 on 2023-01-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_remove_review_product_remove_review_rating_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
